# Mission 1

Find a way to calculate the following statistical indicators for any given one-dimensional array using NumPy functions, and use them on a array filled with 20 random floats.
- mode
- median
- average
- the range (the difference between max and min)
- standard deviation
- variance
- the different quantiles

Then, create another array with 20 random floats and calculate the Pearson coefficient between the two arrays.

In [1]:
import numpy as np

In [16]:
arr1 = np.random.rand(20)
arr1

array([0.03551518, 0.88724605, 0.8723338 , 0.34617078, 0.13085624,
       0.69553219, 0.87420887, 0.12047194, 0.26273863, 0.26286738,
       0.64530676, 0.41425079, 0.35947641, 0.09476547, 0.70157834,
       0.7307948 , 0.16363845, 0.11789286, 0.08719604, 0.48922862])

In [17]:
# MODE

# utilisation de np.unique() qui retourne les valeurs unique de l'array, ajout de return_counts = True pour compter le nombre de fois qu'elles apparaissent 
value, count = np.unique(arr1, return_counts= True)

# on recherche la valeur max dans le compteur avec argmax qui renvoie l'index de cette valeur
index = np.argmax(count)

# je retourne la valeur à cet index
value[index]

0.035515177047333646

In [18]:
# vérification avec scipy
from scipy import stats

mode = stats.mode(arr1)
print(mode[0])

[0.03551518]


In [19]:
# MEDIAN
np.median(arr1)

0.35282359750962417

In [20]:
# AVERAGE
np.average(arr1)

0.41460348006253794

In [21]:
# RANGE
range = np.amax(arr1) - np.amin(arr1)
range

0.8517308688683647

In [22]:
# STANDARD DEVIATION
np.std(arr1)

0.29062397386010325

In [23]:
# VARIANCE
np.var(arr1)

0.08446229418223797

In [24]:
# DIFFERENT QUANTILES
print(np.quantile(arr1, 0.25))
print(np.quantile(arr1, 0.5))
print(np.quantile(arr1, 0.75))

0.1282601629959437
0.35282359750962417
0.6970437296731534


In [25]:
arr2 = np.random.rand(20)
print(arr1)
print(arr2)

# COEFF PEARSON
coeff_array = np.corrcoef(arr1, arr2)
print(coeff_array)

[0.03551518 0.88724605 0.8723338  0.34617078 0.13085624 0.69553219
 0.87420887 0.12047194 0.26273863 0.26286738 0.64530676 0.41425079
 0.35947641 0.09476547 0.70157834 0.7307948  0.16363845 0.11789286
 0.08719604 0.48922862]
[0.37290059 0.37729354 0.13612498 0.8389629  0.78914902 0.70494268
 0.4316009  0.65791868 0.1857398  0.10187756 0.77435465 0.44843709
 0.09074591 0.1420336  0.84796743 0.13020083 0.18337958 0.51898987
 0.84746002 0.57449606]
[[ 1.         -0.02806097]
 [-0.02806097  1.        ]]


## Mission 2

Create a function using NumPy that indicates the values (integers only), from -100 to 100, where the remainder from performing Euclidean division by both 3 and 7 is equal.

In [15]:

def remainder_euclidean(array):
  # création de 2 array (un des reste de division par 3 et un des restes de division par 7)
  remainder_by_3 = np.remainder(array, 3)
  remainder_by_7 = np.remainder(array, 7)

  #création liste vide où je vais stocker les index des valeurs égales dans les arrays
  list_vide = []
  for i in range(len(array)):
    if remainder_by_3[i] == remainder_by_7[i]:
      list_vide.append(i)

  # création d'une liste vide pour stocker les valeurs dont les %3 et %7 sont égales
  list_of_int = []
  for i in range(len(list_vide)):
    list_of_int.append(array[list_vide[i]])
  return list_of_int

array = np.arange(-100, 101)

remainder_euclidean(array)


[-84,
 -83,
 -82,
 -63,
 -62,
 -61,
 -42,
 -41,
 -40,
 -21,
 -20,
 -19,
 0,
 1,
 2,
 21,
 22,
 23,
 42,
 43,
 44,
 63,
 64,
 65,
 84,
 85,
 86]

## Mission 3

Create a function that returns the [inverse value (for `3`, return `1/3`)](https://en.wikipedia.org/wiki/Multiplicative_inverse) of a set of values contained in a NumPy array

In [47]:
def reciproque(array):
  inversed_array = np.power(array, -1)
  return inversed_array


my_array = np.arange(2, 20, dtype=float)
my_array

array([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
       15., 16., 17., 18., 19.])

In [48]:
reciproque(my_array)

array([0.5       , 0.33333333, 0.25      , 0.2       , 0.16666667,
       0.14285714, 0.125     , 0.11111111, 0.1       , 0.09090909,
       0.08333333, 0.07692308, 0.07142857, 0.06666667, 0.0625    ,
       0.05882353, 0.05555556, 0.05263158])