# NumPy : Introduction

**NumPy allows you to manipulate data in the form of an array.**

**Complete the missions below using NumPy.**

In [ ]:

import numpy as np # Here we rename numpy as np, it's shorter, and everybody does that

# Mission 1 : Display the version of NumPy you are running

np.version.version

'1.19.5'

In [ ]:
# Mission 2 : Create a NumPy array with a length of 3, that contains this 3 floats: 0.8, 0.6, 0.4
# Expected result: array([0.8, 0.6, 0.4])

my_array = np.array([0.8, 0.6, 0.4])
my_array

array([0.8, 0.6, 0.4])

In [ ]:
# Mission 3 : Create a function that uses the np.random.random() function to return an array with 10 random elements, 
# all of which must be greater than 0.25 and less than 1.0

# Example of expected result: array([0.3897948 , 0.82850041, 0.5499838 , 0.81940137, 0.92175875, 0.89634373, 0.26821861, 0.72376496, 0.81098623, 0.28192741])

def give_array():
  # Results of np.random.random() are from the “continuous uniform” distribution over the stated interval. 
  # To sample Unif[a, b), b > a multiply the output of random_sample by (b-a) and add a:
  array = 0.75 * np.random.random_sample(10) +0.25
  return array

give_array()

array([0.53778223, 0.61634398, 0.97283799, 0.61672825, 0.74490996,
       0.48287873, 0.62883634, 0.29584042, 0.32223319, 0.98827401])

In [ ]:
# avec une boucle:

def give_array2():
  array = []
  while len(array) < 10:
    num = np.random.random()
    if num > 0.25:
      array.append(num)
      
  return np.array(array)

give_array2()

array([0.97441398, 0.53479138, 0.26200075, 0.96759246, 0.89712276,
       0.51594562, 0.44714362, 0.7808473 , 0.65062139, 0.76797377])

In [ ]:
# Mission 4 : What does the np.empty() method do? Don't just copy the documentation, explain in your own words here

# this methods return a new array of a given shape. The array's values are not initialized. If you print the array, the values will be randomed. You have to set the values.

In [ ]:
# Mission 5 : Create an array filled with only zeros. You can chose the length of this array.

my_zero_array = np.zeros(5)
my_zero_array

array([0., 0., 0., 0., 0.])

In [ ]:
# Mission 6 : Create an array filled with 10 random integers.

my_randint_array = np.random.randint(5, 20, 10)                     # 10 entiers entre 5 et 20
my_randint_array

array([19, 13,  5,  9,  7, 18, 18,  6, 17, 16])

In [ ]:
# Mission 7 : Create an array that contains 50 values randomly selected only from these numbers: 0, 1, 2, 3, 4, 5, 6, 7.

num = [0, 1, 2, 3, 4, 5, 6, 7]

my_new_array = np.random.choice(num, size = (5, 10))
my_new_array


array([[2, 3, 3, 2, 2, 1, 1, 7, 6, 7],
       [4, 1, 3, 4, 7, 6, 7, 1, 6, 7],
       [2, 7, 3, 2, 3, 1, 1, 2, 2, 5],
       [7, 5, 0, 7, 3, 6, 2, 7, 7, 6],
       [3, 0, 2, 2, 0, 6, 0, 0, 5, 2]])

In [ ]:
# Mission 8 : Use the slicing operator to return the items between position 3 and 6 inclusive, from the array in mission 6
my_randint_array[3:7]


array([ 5,  9,  7, 18])

In [ ]:
# Mission 9 : Use the `argmin()` method to return the index of the smallest element in the array from mission 6

my_randint_array.argmin()

2

In [ ]:
# Mission 10 : Using the `where()` method, return the indices of all the values in the array from mission 6 that are greater than their median value.

# la médiane dans l'exemple est 14.5
np.where(my_randint_array > np.median(my_randint_array))

(array([0, 5, 6, 8, 9]),)

In [ ]:
# Mission 11: Create 3 arrays filled with 5 random integers each, and place them in another array.
# You have now an array with (3, 5) shape. You can use the `shape` attribute to check it.
# Display the elements, with each column appearing on a different line (so there will be 5 lines with 3 values each)

array1 = np.random.randint(20, size=5)
array2 = np.random.randint(20, size=5)
array3 = np.random.randint(20, size=5)

big_array = np.vstack((array1, array2, array3))
big_array

array([[15, 17, 16,  7,  6],
       [ 6,  5, 13,  5,  1],
       [ 1,  0, 15, 19,  4]])

In [ ]:
big_array.shape

(3, 5)

In [ ]:
big_array.T

array([[15,  6,  1],
       [17,  5,  0],
       [16, 13, 15],
       [ 7,  5, 19],
       [ 6,  1,  4]])

In [ ]:
# Mission 12: Create an array and fill it with 20 random float values.
# Create a function that returns the smallest and largest value it contains, with their indexes!
# You are allowed to use `min()` and `max()` methods.
# Example with a shorter array: [300, 500, 1000, 700, 100, 600] -> (4, 100), (2, 1000)
# Example with a shorter array: [80, 50, 90, -20, 100, 10] -> (3, -20), (4, 100)

float_array = np.random.rand(20)
float_array

array([0.62212288, 0.52192203, 0.37404906, 0.9298108 , 0.02569996,
       0.12763512, 0.2126693 , 0.15927614, 0.58665427, 0.18333006,
       0.98599332, 0.08763522, 0.88798271, 0.32708992, 0.86038409,
       0.65996816, 0.05633877, 0.23688816, 0.81195988, 0.91722118])

In [ ]:
def min_max_array(array):
  for index, value in enumerate(array):
    if value == array.min():
      index_min, value_min = index, value
  
    if value == array.max():
      index_max, value_max = index, value
  return (index_min, value_min), (index_max, value_max)
  
min_max_array(float_array)


((4, 0.02569996075679537), (10, 0.9859933191509485))

In [ ]:
# Mission 13: Create 2 arrays, randomly fill them with 20 int values between 0 and 10.
# Create a function that will go through each array using a for loop.
# At each iteration of the loop the function should compare the values of the 2 arrays located at the same index position.
# Return all indices where the values of the 2 arrays happen to be equal, in a list.
# If no values are equal at the same indices across the 2 arrays, that list will be empty.
# Example with shorter arrays: [1, 3, 5, 7] & [2, 3, 5, 8] -> [1, 2]
# Example with shorter arrays: [1, 1, 1, 1] & [1, 2, 3, 4] -> [0]

array1 = np.random.randint(10, size=(20))
array2 = np.random.randint(10, size=(20))

print(f'array 1: {array1}')
print(f'array 2: {array2}')

def equals_in_array(arr1, arr2):
  equal_list= []
  for i in range(20):
    if arr1[i] == arr2[i]:
      equal_list.append(i)
  return equal_list

equals_in_array(array1, array2)

array 1: [5 4 8 2 9 3 0 1 7 2 2 4 7 1 8 7 6 4 6 3]
array 2: [8 7 8 7 8 6 5 6 0 4 1 6 6 2 8 1 8 9 2 8]


[2, 14]

In [ ]:
# Mission 14: now, just compare both arrays of mission 13 with this command (change the name of arrays): array1 == array2

array1 == array2

array([False, False,  True, False, False, False, False, False, False,
       False, False, False, False, False,  True, False, False, False,
       False, False])